### PR TITLE
- Command to create block culling rule file

### PR DESCRIPTION
**Pull request by Xterionix**
Tried testing locally but couldn't get the extension to run, something to do with the out folder. Let me know if anything's missing

### CODE REVIEW

**Comment by Xterionix** [comment]
Managed to compile and run it but it throws an error about not needing a project that has a manifest but I do so I'm not sure what's wrong.

**Review by DaanV2 — COMMENTED** [review]
1. To help you with the compiling, I might need to see output of the console log
2. Can you add in `server/src/Lib/Commands/Templates/Templates.ts`  the command to an template

**Comment by Xterionix** [comment]
Alr I'll do that

**Comment by Xterionix** [comment]
It compiles but running the command doesn't seem to do anything, not sure what I'm doing wrong

**Review by DaanV2 — APPROVED** [review]

**Pull request merged**
